version: '3.8'
services:
  easepay-signet:
    ports:
      - "28332:28332" # ZMQ block publish port
      - "28333:28333" # ZMQ transaction publish port
      - "38332:38332" # RPC port 
  fulcrum:
    ports:
    - "127.0.0.1:50001:50001"
    - "127.0.0.1:50002:50002"