version: '3.8'
services:
  easepay-signet:
    image: elyanekenimoh/easepay-signet-node
    command: run.sh
    volumes:
      - easepay_signet_data:/root/.bitcoin
    env_file:
      - signet.env
    restart: on-failure  # Ensures the container restarts if it exits due to an error

  wallet-setup:
    image: elyanekenimoh/easepay-signet-node
    env_file:
      - signet.env
      - wallet_setup.env
    entrypoint:
      - sh
      - -c
      - |
        bitcoin-cli -rpcuser=$${RPC_USER} -rpcpassword=$${RPCPASSWORD} -rpcconnect=$${RPCADDR} -signet -named createwallet wallet_name=$${WALLET_NAME} descriptors=false
        bitcoin-cli -rpcuser=$${RPCUSER} -rpcpassword=$${RPCPASSWORD} -rpcconnect=$${RPCADDR} -signet -named importprivkey $${PRIVKEY}
    depends_on:
      - easepay-signet

  miner:
    image: elyanekenimoh/easepay-signet-node
    env_file:
      - miner.env
    entrypoint:
      - sh
      - -c
      - miner --cli="bitcoin-cli -rpcuser=$${RPCUSER} -rpcpassword=$${RPCPASSWORD} -rpcconnect=$${RPC_ADDR}" generate --address $${REWARDS_BTC_ADDRESS} --grind-cmd="bitcoin-util grind" --nbits=$${MINING_DIFFICULTY} --ongoing
    restart: on-failure

  fulcrum:
    image: cculianu/fulcrum:latest
    command: --conf /etc/fulcrum.conf
    ports:
      - 127.0.0.1:50001:50001
      - 127.0.0.1:50002:50002
    restart: on-failure
    volumes:
      - ./fulcrum.conf:/etc/fulcrum.conf
      - fulcrum_data:/var/lib/fulcrum

  mempool-web:
    image: mempool/frontend:v3.0.0-dev8
    environment:
      - BACKEND_MAINNET_HTTP_HOST=mempool-api
      - FRONTEND_HTTP_PORT=8080
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure

  mempool-api:
    image: mempool/backend:v3.0.0-dev8
    environment:
      - CORE_RPC_HOST=easepay-signet
      - CORE_RPC_PASSWORD=$(RPCPASSWORD}
      - CORE_RPC_PORT=38332
      - CORE_RPC_USERNAME=easepay-signet
      - DATABASE_DATABASE=mempool
      - DATABASE_ENABLED=true
      - DATABASE_HOST=mariadb
      - DATABASE_PASSWORD=mempool
      - DATABASE_USERNAME=mempool
      - ELECTRUM_HOST=fulcrum
      - ELECTRUM_PORT=50001
      - ELECTRUM_TLS_ENABLED=false
      - MEMPOOL_BACKEND=electrum
      - MEMPOOL_NETWORK=signet
      - STATISTICS_ENABLED=false
    restart: on-failure

  mariadb:
    image: mariadb:11.3
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=mempool
      - MARIADB_PASSWORD=mempool
      - MARIADB_USER=mempool
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    restart: on-failure

  mongo:
    image: mongo:7.0
    restart: on-failure
    volumes:
      - mongo_data:/data

  faucet:
    image: 1maa/signet-faucet:latest
    environment:
      - BITCOIND_HOST=easepay-signet
      - BITCOIND_USER=easepay-signet
      - BITCOIND_PASS=Beautifulgirl456
      - MONGODB_HOST=mongo
    ports:
      - 127.0.0.1:8123:8123
    restart: on-failure

volumes:
  fulcrum_data:
  easepay_signet_data:
  mariadb_data:
  mongo_data: